site:
  title: Regis CLI
  url: https://trivoallan.github.io/regis-cli/
  start_page: regis-cli::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
antora:
  extensions:
    - require: "@sntke/antora-mermaid-extension"
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
      script_stem: header-scripts

output:
  dir: ./build/site
